spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: password
    pool:
      enabled: true
      initial-size: 20
      max-size: 500
      max-idle-time: 30m
  datasource:
    initialization-mode: always
  sql:
    init:
      platform: mysql
      mode: always
server:
  port: 8080
logging:
  level:
    root: INFO
